'use client';

import { useEffect } from 'react';
import { useTranslation } from '@/i18n';
import en from '@/i18n/translations/en.json';
import tr from '@/i18n/translations/tr.json';

/**
 * Compatibility translator for legacy dashboard chrome that predates the i18n layer.
 *
 * It intentionally translates only short, exact UI labels / attributes. Article
 * titles, intelligence records, callsigns, source names and free-form telemetry are
 * never machine-translated here, so source fidelity is preserved.
 */
function flattenTranslations(value: unknown, prefix = '', out: Record<string, string> = {}): Record<string, string> {
  if (!value || typeof value !== 'object') return out;
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof child === 'string') out[path] = child;
    else flattenTranslations(child, path, out);
  }
  return out;
}

const EN_FLAT = flattenTranslations(en);
const TR_FLAT = flattenTranslations(tr);
const I18N_REVERSE: Record<string, string> = Object.fromEntries(
  Object.entries(EN_FLAT)
    .filter(([key, value]) => Boolean(value) && Boolean(TR_FLAT[key]) && value !== TR_FLAT[key])
    .map(([key, value]) => [value.trim(), TR_FLAT[key].trim()]),
);

const EXACT: Record<string, string> = {
  'MISSION BRIEFING': 'GÖREV BRİFİNGİ',
  'FIRST-TIME SETUP': 'İLK KURULUM',
  'API KEYS': 'API ANAHTARLARI',
  'AI AGENT': 'YZ AJANI',
  'FREE SOURCES': 'ÜCRETSİZ KAYNAKLAR',
  'DATA LAYERS': 'VERİ KATMANLARI',
  'MARITIME': 'DENİZCİLİK',
  'SPACE': 'UZAY',
  'THREATS': 'TEHDİTLER',
  'MESHTASTIC CHAT': 'MESHTASTIC SOHBETİ',
  'SHELL': 'KABUK',
  'DISCOVERY TOOLS': 'KEŞİF ARAÇLARI',
  'SUPPLY CHAIN': 'TEDARİK ZİNCİRİ',
  'AI INTELLIGENCE PANEL': 'YZ İSTİHBARAT PANELİ',
  'CONNECT OPENCLAW': 'OPENCLAW BAĞLA',
  'TIME MACHINE': 'ZAMAN MAKİNESİ',
  'DATA FILTERS': 'VERİ FİLTRELERİ',
  'NO NEWS ITEMS LOADED': 'HENÜZ HABER YÜKLENMEDİ',
  'Feed ingest is empty or still warming up.': 'Haber akışı boş veya henüz hazırlanıyor.',
  'SCANNING': 'TARANIYOR',
  'QUICK LOCAL SETUP': 'HIZLI YEREL KURULUM',
  'SAVE KEYS LOCALLY': 'ANAHTARLARI YERELDE KAYDET',
  'SAVING...': 'KAYDEDİLİYOR...',
  'START HERE': 'BURADAN BAŞLA',
  'PREV': 'GERİ',
  'NEXT': 'İLERİ',
  'REQUIRED': 'ZORUNLU',
  'OPTIONAL': 'İSTEĞE BAĞLI',
  'GET KEY': 'ANAHTAR AL',
  'OPEN SETTINGS TO ENTER KEYS': 'ANAHTARLARI GİRMEK İÇİN AYARLARI AÇ',
  'DISPLAY CONFIG': 'GÖRÜNTÜ AYARLARI',
  'CLEAR UI (TACTICAL MODE)': 'ARAYÜZÜ TEMİZLE (TAKTİK MOD)',
  'LAYOUT': 'DÜZEN',
  'Tactical': 'Taktik',
  'ON': 'AÇIK',
  'OFF': 'KAPALI',
  'LIVE': 'CANLI',
  'LOCAL': 'YEREL',
  'READY': 'HAZIR',
  'ALERT': 'UYARI',
  'QUIET': 'SAKİN',
  'OFFLINE': 'ÇEVRİMDIŞI',
  'ONLINE': 'ÇEVRİMİÇİ',
  'NEVER RECEIVED': 'HENÜZ VERİ ALINMADI',
  'AIRCRAFT MODEL': 'HAVA ARACI MODELİ',
  'DATA LINK (AIRFRAMES)': 'VERİ BAĞLANTISI (AIRFRAMES)',
  'FLIGHT HISTORY': 'UÇUŞ GEÇMİŞİ',
  'UNKNOWN': 'BİLİNMİYOR',
  'Unknown': 'Bilinmiyor',
  'Unknown Region': 'Bilinmeyen Bölge',
  'Unknown service': 'Bilinmeyen servis',
  'Loading...': 'Yükleniyor...',
  'Loading full host detail...': 'Ayrıntılı kayıt yükleniyor...',
  'Save failed': 'Kaydetme başarısız',
  'Request failed': 'İstek başarısız',
  'Connection failed': 'Bağlantı başarısız',
  'Save Label': 'Etiketi Kaydet',
  'UI language': 'Arayüz dili',
  'Open in browser': 'Tarayıcıda aç',
  'Open source': 'Kaynağı aç',
  'Checking...': 'Kontrol ediliyor...',
  'Active': 'Aktif',
  'Inactive': 'Pasif',
  'Push Task to Agent': 'Görevi Ajana Gönder',
  'Connect OpenClaw Agent': 'OpenClaw Ajanını Bağla',
  'No recent pathogen data available': 'Yakın zamana ait patojen verisi yok',
  'No facet buckets returned.': 'Filtre grubu sonucu dönmedi.',
  'No data available.': 'Kullanılabilir veri yok.',
  'CLICK THE MAP TO PLACE AOI CENTER': 'İLGİ ALANI MERKEZİNİ YERLEŞTİRMEK İÇİN HARİTAYA TIKLAYIN',
  'I understand this message is public and not private.': 'Bu mesajın özel değil, herkese açık olduğunu anlıyorum.',
  'No comments yet.': 'Henüz yorum yok.',
  'Replying to comment…': 'Yoruma yanıt veriliyor…',
  'No stories in wire feed.': 'Haber akışında içerik yok.',
  'No market data available.': 'Kullanılabilir piyasa verisi yok.',
  'Failed to load:': 'Yükleme başarısız:',
  'No upgrade proposals on chain.': 'Zincirde yükseltme önerisi yok.',
  'Failed to load petitions': 'Dilekçeler yüklenemedi',
  'No petitions on the chain yet.': 'Zincirde henüz dilekçe yok.',
  'PUBLIC / DEGRADED': 'GENEL / SINIRLI',
  'PRIVATE / TRANSITIONAL': 'ÖZEL / GEÇİŞ AŞAMASI',
  'PRIVATE / STRONG': 'ÖZEL / GÜÇLÜ',
  'STATUS': 'DURUM',
  'SOURCE': 'KAYNAK',
  'SOURCES': 'KAYNAKLAR',
  'LOCATION': 'KONUM',
  'REGION': 'BÖLGE',
  'CATEGORY': 'KATEGORİ',
  'TYPE': 'TÜR',
  'TIME': 'ZAMAN',
  'DATE': 'TARİH',
  'ROUTE': 'ROTA',
  'ORIGIN': 'KALKIŞ',
  'DESTINATION': 'VARIŞ',
  'ALTITUDE': 'İRTİFA',
  'HEADING': 'YÖN',
  'GROUND SPEED': 'YER HIZI',
  'SPEED (SOG)': 'HIZ (SOG)',
  'REGISTRATION': 'TESCİL',
  'CALLSIGN': 'ÇAĞRI KODU',
  'OPERATOR': 'OPERATÖR',
  'VESSEL NAME': 'GEMİ ADI',
  'VESSEL TYPE': 'GEMİ TÜRÜ',
  'VESSEL RECORD': 'GEMİ KAYDI',
  'FLIGHT RECORD': 'UÇUŞ KAYDI',
  'AIRCRAFT': 'HAVA ARACI',
  'SHIP': 'GEMİ',
  'SATELLITE': 'UYDU',
  'SATELLITE IMAGERY': 'UYDU GÖRÜNTÜSÜ',
  'BREAKING': 'SON DAKİKA',
  'TOP STORIES': 'ÖNE ÇIKAN HABERLER',
  'TRENDING KEYWORDS': 'GÜNDEMDEKİ ANAHTAR KELİMELER',
  'REFRESH': 'YENİLE',
  'SEARCH': 'ARA',
  'SAVE': 'KAYDET',
  'DELETE': 'SİL',
  'CLOSE': 'KAPAT',
  'RESTORE': 'GERİ YÜKLE',
  'SETTINGS': 'AYARLAR',
  'REFERENCE': 'REFERANS',
  'REPORTED TIME': 'BİLDİRİM ZAMANI',
  'RISK LEVEL': 'RİSK SEVİYESİ',
  'THREAT BREAKDOWN': 'TEHDİT DAĞILIMI',
  'THREAT DRIVERS': 'TEHDİT ETKENLERİ',
  'THREAT ACTORS': 'TEHDİT AKTÖRLERİ',
  'REGION INTEL': 'BÖLGE İSTİHBARATI',
  'REGION DOSSIER': 'BÖLGE DOSYASI',
  'CONFLICT': 'ÇATIŞMA',
  'UNREST': 'TOPLUMSAL OLAY',
  'TECH': 'TEKNOLOJİ',
  'SOCIALS': 'SOSYAL',
  'TARGETS': 'HEDEFLER',
  'TAGS': 'ETİKETLER',
  'PRODUCT': 'ÜRÜN',
  'PORTS': 'PORTLAR',
  'STATE/PROVINCE': 'EYALET/İL',
  'TEST CONNECTION': 'BAĞLANTIYI TEST ET',
  'SAVE AS DEFAULT': 'VARSAYILAN OLARAK KAYDET',
  'SAVE RUNTIME PROFILE': 'ÇALIŞMA PROFİLİNİ KAYDET',
  'PULL MODEL': 'MODELİ İNDİR',
  'SUMMARIZE LOCALLY': 'YERELDE ÖZETLE',
  'REINDEX LOCAL VECTORS': 'YEREL VEKTÖRLERİ YENİDEN İNDEKSLE',
  'REBUILD SEARCH + OPTIMIZE': 'ARAMAYI YENİDEN OLUŞTUR + OPTİMİZE ET',
  'SHUTDOWN': 'KAPAT',
  'SUSPEND': 'ASKIYA AL',
  'WELCOME': 'HOŞ GELDİNİZ',
  'INFO': 'BİLGİ',
  'DETAILS': 'DETAYLAR',
  'MODEL': 'MODEL',
  'CLASSIFICATION': 'SINIFLANDIRMA',
  'ACTIVE': 'AKTİF',
  'PAUSED': 'DURAKLATILDI',

  'YES': 'EVET',
  'NO': 'HAYIR',
  'SCALE': 'ÖLÇEK',
  'SQUAWK': 'TRANSPONDER KODU',
  'SENTIMENT': 'DUYGU ANALİZİ',
  'ORG': 'KURUM',
  'ORACLE SCORE': 'ORACLE PUANI',
  'PORT': 'LİMAN',
  'ISP': 'İNTERNET SAĞLAYICI',
  'ASN': 'ASN',
  'WITNESS REPORT': 'TANIK RAPORU',
  'VULNS': 'AÇIKLAR',
  'VOTING': 'OYLAMA',
  'TRUST MODES': 'GÜVEN MODLARI',
  'TRACKED YACHT': 'TAKİP EDİLEN YAT',
  'THREAD SNAPSHOT': 'AKIŞ ANLIK GÖRÜNTÜSÜ',
  'TEST-NET ACTIVE': 'TEST AĞI ETKİN',
  'SYS.STATUS: MONITORING': 'SİSTEM DURUMU: İZLENİYOR',
  'SYNC LOOP': 'EŞİTLEME DÖNGÜSÜ',
  'STORE': 'DEPO',
  'STORAGE:': 'DEPOLAMA:',
  'SNAPSHOTS': 'ANLIK GÖRÜNTÜLER',
  'SIGNATURES': 'İMZALAR',
  'SIGINT INTERCEPT': 'SIGINT YAKALAMA',
  'SEEN': 'GÖRÜLDÜ',
  'SCENARIOS': 'SENARYOLAR',
  'SAR GROUND-CHANGE STATUS': 'SAR ZEMİN DEĞİŞİM DURUMU',
  'SAR AREAS OF INTEREST': 'SAR İLGİ ALANLARI',
  'RETURN TO CHANNEL': 'KANALE DÖN',
  'RELATIONSHIPS': 'İLİŞKİLER',
  'REDUCED TRUST:': 'AZALTILMIŞ GÜVEN:',
  'RECENT REPOSITORIES': 'SON DEPOLAR',
  'PUBLIC MESH LANE': 'GENEL MESH HATTI',
  'PUBLIC MESH': 'GENEL MESH',
  'PREDICTION MARKET SIGNALS': 'TAHMİN PİYASASI SİNYALLERİ',
  'POSTERIOR RISK': 'SONSAL RİSK',
  'POPULATION': 'NÜFUS',
  'POLITICS': 'SİYASET',
  'PINNED': 'SABİTLENMİŞ',
  'PENDING': 'BEKLİYOR',
  'PEERS': 'EŞLER',
  'PATHOGEN DETECTIONS': 'PATOJEN TESPİTLERİ',
  'ORDER BOOK': 'EMİR DEFTERİ',
  'ORACLE INTEL': 'ORACLE İSTİHBARATI',
  'OPTIMIZE DB': 'VERİTABANINI OPTİMİZE ET',
  'OPS / DOSSIER': 'OPERASYON / DOSYA',
  'OPERATOR SHELL': 'OPERATÖR KABUĞU',
  'OPERATIONAL': 'OPERASYONEL',
  'OFFICIAL STATEMENT': 'RESMÎ AÇIKLAMA',
  'OFFICIAL': 'RESMÎ',
  'NOT CALIBRATED': 'KALİBRE EDİLMEMİŞ',
  'NODE ADDRESS': 'DÜĞÜM ADRESİ',
  'NEW AOI': 'YENİ İLGİ ALANI',
  'NEVER PUBLIC': 'ASLA GENEL DEĞİL',
  'NEAR ME': 'YAKINIMDA',
  'NAME': 'AD',
  'MARKET DETAIL': 'PİYASA DETAYI',
  'MARKET CORRELATION': 'PİYASA KORELASYONU',
  'MAPPED HOSTS': 'HARİTALANAN SUNUCULAR',
  'MANEUVER DETECTED': 'MANEVRA TESPİT EDİLDİ',
  'LONGITUDE': 'BOYLAM',
  'LOCALITY': 'YERLEŞİM',
  'LOCAL SHELL': 'YEREL KABUK',
  'LOCAL LEVEL': 'YEREL SEVİYE',
  'LOCAL ANALYST WORKSPACE': 'YEREL ANALİST ÇALIŞMA ALANI',
  'LOCAL AI': 'YEREL YZ',
  'LIVE MARKET CARDS': 'CANLI PİYASA KARTLARI',
  'LIVE ADS-B TRANSPONDER': 'CANLI ADS-B TRANSPONDER',
  'LEADER': 'LİDER',
  'LATITUDE': 'ENLEM',
  'LATEST NARRATIVES': 'SON ANLATILAR',
  'LANGUAGES': 'DİLLER',
  'KEY SETUP': 'ANAHTAR KURULUMU',
  'KEY INDICATORS': 'TEMEL GÖSTERGELER',
  'KEY': 'ANAHTAR',
  'INTENSITY': 'YOĞUNLUK',
  'INTELLIGENCE CORE': 'İSTİHBARAT MERKEZİ',
  'INTEL UNAVAILABLE': 'İSTİHBARAT KULLANILAMIYOR',
  'INTEL TAGS': 'İSTİHBARAT ETİKETLERİ',
  'INPUT': 'GİRDİ',
  'HEALTH SCORE': 'SAĞLIK PUANI',
  'HEADLINE': 'BAŞLIK',
  'HASH & CAPTURE EVIDENCE': 'KANITI ÖZETLE & KAYDET',
  'GOVERNMENT': 'DEVLET',
  'GLOBAL THREAT INTERCEPT': 'KÜRESEL TEHDİT İZLEME',
  'FUEL BURNED': 'YAKIT TÜKETİMİ',
  'FLAG STATE': 'BAYRAK DEVLETİ',
  'FINANCE': 'FİNANS',
  'FACILITY NAME': 'TESİS ADI',
  'FACETS': 'BOYUTLAR',
  'EXECUTED': 'UYGULANDI',
  'EVIDENCE CHAIN': 'KANIT ZİNCİRİ',
  'EVIDENCE': 'KANIT',
  'EVENTS': 'OLAYLAR',
  'EMISSIONS ESTIMATE': 'EMİSYON TAHMİNİ',
  'DOMAINS': 'ALAN ADLARI',
  'DISPUTE': 'ANLAŞMAZLIK',
  'DIRECT': 'DOĞRUDAN',
  'DEPARTURE': 'KALKIŞ',
  'COUNTRY': 'ÜLKE',
  'CITY': 'ŞEHİR',
  'CONFIDENCE': 'GÜVEN',
  'COORDINATES': 'KOORDİNATLAR',
  'CURRENT POSITION': 'MEVCUT KONUM',
  'CURRENT STATUS': 'MEVCUT DURUM',
  'CLOSE PANEL': 'PANELİ KAPAT',
  'CLEAR': 'TEMİZLE',
  'BACK': 'GERİ',
  'APPLY': 'UYGULA',
  'ALERTS': 'UYARILAR',
  'ANALYSIS': 'ANALİZ',
  'AIRPORT': 'HAVALİMANI',
  'AIRPORTS': 'HAVALİMANLARI',
  'DATALINK (AIRFRAMES)': 'VERİ BAĞLANTISI (AIRFRAMES)',
  'MESHTASTIC MQTT': 'MESHTASTIC MQTT',
  'MQTT OFF': 'MQTT KAPALI',
  'MQTT LIVE': 'MQTT CANLI',
  'MQTT CONNECTING': 'MQTT BAĞLANIYOR',
  'MQTT STARTING': 'MQTT BAŞLATILIYOR',
  'BROKER': 'SUNUCU',
  'BROKER LOGIN (optional)': 'SUNUCU KULLANICISI (isteğe bağlı)',
  'DEFAULT PUBLIC ROOTS': 'VARSAYILAN GENEL KÖKLER',
  'EXTRA ROOTS': 'EK KÖKLER',
  'ENABLE': 'ETKİNLEŞTİR',
  'DISABLE': 'DEVRE DIŞI BIRAK',
  'BROADCAST': 'YAYINLA',
  'CHAIN': 'ZİNCİR',
  'COMMAND LINE': 'KOMUT SATIRI',
  'CREATOR': 'OLUŞTURAN',
  'Creator': 'Oluşturan',
  'MESSAGES': 'MESAJLAR',
  'Messages': 'Mesajlar',
  'Epoch': 'Dönem',
  'Access': 'Erişim',
  'Bootstrap': 'Başlangıç Eşi',
  'Last peer': 'Son eş',
  'What this does': 'Bu ne yapar',
  'Minimize terminal': 'Terminali küçült',
  'EXPERIMENTAL PRIVATE DM INBOX': 'DENEYSEL ÖZEL DM GELEN KUTUSU',
  'CONTACT CARDS': 'KİŞİ KARTLARI',
  'ALL': 'TÜMÜ',
  'NONE': 'YOK',
  'OPEN': 'AÇIK',
  'CANCEL': 'İPTAL',
  'CONNECTING': 'BAĞLANIYOR',
  'BLOCKED': 'ENGELLENDİ',
  'CRITICAL': 'KRİTİK',
  'ELEVATED': 'YÜKSEK',
  'SEVERE': 'CİDDİ',
  'NEWS': 'HABERLER',
  'MARKETS': 'PİYASALAR',
  'PROFILE': 'PROFİL',
  'LOCKED': 'KİLİTLİ',
  'UNMAPPED': 'HARİTALANMAMIŞ',
  'MILITARY': 'ASKERÎ',
  'COMMERCIAL FLIGHT': 'TİCARİ UÇUŞ',
  'LOCAL ONLY': 'YALNIZCA YEREL',
  'FAIL': 'BAŞARISIZ',
  'DOMAIN': 'ALAN ADI',
  'BUY': 'AL',
  'SELL': 'SAT',
  'CREDITS': 'KREDİLER',
  'BALLOT': 'OYLAMA',
  'TRANSPORT': 'AKTARIM',
  'ALERT LVL': 'UYARI SEVİYESİ',
  'ACTIVE THREATS IN AREA': 'BÖLGEDE AKTİF TEHDİT',
  'HIGH': 'YÜKSEK',
  'MEDIUM': 'ORTA',
  'LOW': 'DÜŞÜK',
  'WARNING': 'UYARI',
  'DEFAULT': 'VARSAYILAN',
  'LOCATE': 'KONUMA GİT',
  'CHANNEL': 'KANAL',
  'INBOX': 'GELEN KUTUSU',
  'MESSAGE': 'MESAJ',
  'OPEN SHELL': 'KABUĞU AÇ',
  'RECONNECT': 'YENİDEN BAĞLAN',
  'SCANNING...': 'TARANIYOR...',
  'AUTO SCAN': 'OTOMATİK TARA',
  'NO ACTIVE AIRCRAFT': 'AKTİF HAVA ARACI YOK',
  'OPEN SETTINGS': 'AYARLARI AÇ',
  'OPEN WORMHOLE': 'WORMHOLE AÇ',
  'ENTER WORMHOLE': 'WORMHOLE’A GİR',
  'OPEN DM': 'ÖZEL MESAJ AÇ',
  'LIVE CAPTURE ON': 'CANLI KAYIT AÇIK',
  'SNAPSHOTS OFF': 'ANLIK GÖRÜNTÜLER KAPALI',
  'SNAPSHOTS ON': 'ANLIK GÖRÜNTÜLER AÇIK',
  'SNAPSHOT': 'ANLIK GÖRÜNTÜ',
  'VERY SLOW': 'ÇOK YAVAŞ',
  'CO2 EMITTED': 'SALINAN CO₂',
  'COMPILING INTELLIGENCE...': 'İSTİHBARAT DERLENİYOR...',
  'CAPITAL': 'BAŞKENT',
  'CURRENCY': 'PARA BİRİMİ',
  'AREA': 'ALAN',
  'STRATEGIC RISK (GT)': 'STRATEJİK RİSK (GT)',
  'COSTLY SIGNALS': 'YÜKSEK MALİYETLİ SİNYALLER',
  'SHODAN HOST DOSSIER': 'SHODAN SUNUCU DOSYASI',
  'ATTRIBUTION': 'KAYNAK / ATIF',
  'HOST': 'SUNUCU',
  'HOSTNAMES': 'SUNUCU ADLARI',
  'ALL PORTS': 'TÜM PORTLAR',
  'SERVICES': 'HİZMETLER',
  'IMO NUMBER': 'IMO NUMARASI',
  'COURSE (COG)': 'ROTA AÇISI (COG)',
  'REGIONAL TACTICAL EVENT': 'BÖLGESEL TAKTİK OLAY',
  'DESCRIPTION': 'AÇIKLAMA',
  'THREAT INTERCEPT': 'TEHDİT YAKALAMA',
  'AERONAUTICAL HUB': 'HAVACILIK MERKEZİ',
  'AI INTELLIGENCE BRIEF': 'YZ İSTİHBARAT ÖZETİ',
  'COMPILING INTELLIGENCE BRIEF...': 'İSTİHBARAT ÖZETİ HAZIRLANIYOR...',
  'WORMHOLE OBFUSCATED LANE': 'WORMHOLE GİZLENMİŞ HATTI',
  'MESH ROOT CARDS': 'MESH KÖK KARTLARI',
  'LISTEN': 'DİNLE',
  'SELECT': 'SEÇ',
  'BOARD': 'PANO',
  'REPLY': 'YANITLA',
  'GATES (EXPERIMENTAL ENCRYPTION)': 'GEÇİTLER (DENEYSEL ŞİFRELEME)',
  'OPEN GATE LOG': 'GEÇİT GÜNLÜĞÜNÜ AÇ',
  'POST': 'GÖNDER',
  'UNLOCK': 'KİLİDİ AÇ',
  'EXPERIMENTAL ENCRYPTION': 'DENEYSEL ŞİFRELEME',
  'THREAD': 'AKIŞ',
  'DOWN': 'KAPALI',
  'STAY PUBLIC': 'GENEL HATTA KAL',
  'ADVANCED': 'GELİŞMİŞ',
  'ENTER INFONET COMMONS': 'INFONET ORTAK ALANINA GİR',
  'TERMINAL': 'TERMİNAL',
  'PRIVATE DM INBOX': 'ÖZEL MESAJ GELEN KUTUSU',
  'READ ONLY': 'SALT OKUNUR',
  'RUNNING': 'ÇALIŞIYOR',
  'THE INFONET COMMONS': 'INFONET ORTAK ALANI',
  'PARTICIPANT NODE': 'KATILIMCI DÜĞÜM',
  'PRIVATE SEED LANE': 'ÖZEL TOHUM HATTI',
  'MESH / RADIO': 'MESH / RADYO',
  'GATES / COMMONS': 'GEÇİTLER / ORTAK ALAN',
  'SCANNER TRACKER': 'TARAYICI TAKİBİ',
  'TUNING': 'FREKANS AYARLANIYOR',
  'RELEASE': 'SERBEST BIRAK',
  'SDR TRACKER': 'SDR TAKİBİ',
  'TUNE IN': 'DİNLE',
  'EDIT': 'DÜZENLE',
  'POTUS FLEET': 'ABD BAŞKANLIK FİLOSU',
  'HIDE': 'GİZLE',
  'TRACK': 'TAKİP ET',
  'SHOW': 'GÖSTER',
  'MILITARY ASSET': 'ASKERÎ VARLIK',
  'PRIVATE JET': 'ÖZEL JET',
  'PRIVATE / GA': 'ÖZEL / GENEL HAVACILIK',
  'CARGO VESSEL': 'YÜK GEMİSİ',
  'PASSENGER / CRUISE': 'YOLCU / KRUVAZİYER',
  'PRIVATE YACHT': 'ÖZEL YAT',
  'MILITARY VESSEL': 'ASKERÎ GEMİ',
  'AIRCRAFT CARRIER': 'UÇAK GEMİSİ',
  'AIS TANKER INTERCEPT': 'AIS TANKER İZİ',
  'AIS CARGO INTERCEPT': 'AIS YÜK GEMİSİ İZİ',
  'AIS PASSENGER VESSEL': 'AIS YOLCU GEMİSİ',
  'AIS YACHT SIGNAL': 'AIS YAT SİNYALİ',
  'AIS MILITARY VESSEL': 'AIS ASKERÎ GEMİ',
  'CARRIER STRIKE GROUP': 'UÇAK GEMİSİ GRUBU',
  'AIS VESSEL SIGNAL': 'AIS GEMİ SİNYALİ',
  'SLOW': 'YAVAŞ',
  'SEARCHING': 'ARANIYOR',
  'EXPERIMENTAL': 'DENEYSEL',
  'HARDWARE REQUIRED': 'DONANIM GEREKLİ',
  'SOURCE LIMITED': 'KAYNAK SINIRLI',
  'DISABLED BY DESIGN': 'TASARIM GEREĞİ KAPALI',
  'WARMING': 'ISINIYOR',
  'STALE': 'BAYAT',
  'RATE LIMITED': 'KOTA SINIRLI',
  'AUTH REQUIRED': 'KİMLİK DOĞRULAMA GEREKLİ',
  'DEGRADED': 'KISMEN ÇALIŞIYOR',
  'ERROR': 'HATA',
  'CREATE CASE': 'DOSYA OLUŞTUR',
  'CREATE GEOFENCE': 'COĞRAFİ SINIR OLUŞTUR',
  'CREATE RULE': 'KURAL OLUŞTUR',
  'CAPTURE EVIDENCE': 'KANIT KAYDET',
  'SAFE RULE BUILDER': 'GÜVENLİ KURAL OLUŞTURUCU',
  'GLOBAL / SEMANTIC LOCAL SEARCH': 'KÜRESEL / ANLAMSAL YEREL ARAMA',
  'LOCAL AI ANALYST': 'YEREL YZ ANALİSTİ',
  'LOCAL MODEL MANAGER': 'YEREL MODEL YÖNETİCİSİ',
  'ANALYST WORKSPACE PRESETS': 'ANALİST ÇALIŞMA ALANI ÖNAYARLARI',
  'BACKUP': 'YEDEK',
  'DELETE MODEL': 'MODELİ SİL',
  'POST INTO THIS GATE': 'BU GEÇİDE GÖNDER',
  'SEARCH POSTS': 'GÖNDERİLERDE ARA',
  'REASON': 'GEREKÇE',
  'EVIDENCE HASH': 'KANIT ÖZETİ',
  'LOCAL MODEL': 'YEREL MODEL',
  'AVAILABLE LAYERS': 'KULLANILABİLİR KATMANLAR',
  'USAGE LIMITS (FREE TIER)': 'KULLANIM SINIRLARI (ÜCRETSİZ PAKET)',
  'Monthly budget': 'Aylık kota',
  'Cost per tile': 'Karo başına maliyet',
  '~Viewport loads/month': '~Aylık görünüm yüklemesi',
  'Empty tiles': 'Boş karolar',
  'FREE (no data = no charge)': 'ÜCRETSİZ (veri yoksa ücret yok)',
  'HOW IT WORKS': 'NASIL ÇALIŞIR',
  'DESCRIPTION (optional)': 'AÇIKLAMA (isteğe bağlı)',
  'RADIUS (km)': 'YARIÇAP (km)',
  'Farming Score': 'Tarım Puanı',
  'Running game-theoretic analysis...': 'Oyun teorisi analizi çalıştırılıyor...',
  'News Headline': 'Haber Başlığı',
  'Ship data temporarily unavailable': 'Gemi verisi geçici olarak kullanılamıyor',
  'True Color (S2)': 'Gerçek Renk (S2)',
  'False Color IR': 'Sahte Renk IR',
  'Moisture Index': 'Nem İndeksi',
  'loading...': 'yükleniyor...',
  'Identity Active': 'Kimlik Aktif',
  'Node ID:': 'Düğüm Kimliği:',
  'Public Key:': 'Açık Anahtar:',
  'Pending': 'Bekliyor',
  'Completed': 'Tamamlandı',
  'Tasks Queued': 'Sıradaki Görevler',
  'Private link active': 'Özel bağlantı aktif',
  'saving...': 'kaydediliyor...',
  'COPIED': 'KOPYALANDI',
  'COPY': 'KOPYALA',
  'API Endpoint': 'API Uç Noktası',
  'Loading ACARS cache…': 'ACARS önbelleği yükleniyor…',
  'Refreshing this aircraft…': 'Bu hava aracı yenileniyor…',
  '⚠ SYSTEM ERROR': '⚠ SİSTEM HATASI',
  'Style': 'Stil',
  'Presets': 'Önayarlar',
  'Delete preset': 'Önayarı sil',
  'Export:': 'Dışa aktar:',
  'Import': 'İçe aktar',
  'COORDS': 'KOORDİNATLAR',
  'TO YOU': 'SİZE',
  'OPEN SOURCE': 'KAYNAĞI AÇ',
  'NO RESULTS': 'SONUÇ YOK',
  'Try again': 'Tekrar deneyin',
  'Retry': 'Yeniden dene',
  'Not available': 'Kullanılamıyor',
  'Unavailable': 'Kullanılamıyor',
  'Last updated': 'Son güncelleme',
  'Last Update': 'Son Güncelleme',
  'Duration': 'Süre',
  'Arrival': 'Varış',
  'Departure': 'Kalkış',
  'Weather': 'Hava Durumu',
  'Traffic': 'Trafik',
  'Incidents': 'Olaylar',
  'Camera': 'Kamera',
  'Cameras': 'Kameralar',
  'Border': 'Sınır',
  'Borders': 'Sınırlar',
};

const UI_PHRASES: Array<[string, string]> = [
  ['Sentinel-2 revisits every ~5 days — not every location has data every day', 'Sentinel-2 yaklaşık 5 günde bir yeniden geçer — her konumda her gün veri bulunmaz'],
  ['The date slider picks the end of a time window; zoomed out uses wider windows', 'Tarih kaydırıcısı zaman aralığının sonunu seçer; uzaklaştırıldığında daha geniş zaman aralığı kullanılır'],
  ['Black patches = no satellite pass on that date range (normal)', 'Siyah alanlar = seçilen tarih aralığında uydu geçişi yoktur (normal)'],
  ['Best results at zoom 8-14 — closer = sharper imagery (10m resolution)', 'En iyi sonuç yakınlaştırma 8-14 düzeyindedir — yaklaştıkça görüntü keskinleşir (10 m çözünürlük)'],
  ['cloud cover', 'bulut örtüsü'],
  ['No stories in wire feed.', 'Haber akışında içerik yok.'],
  ['No market data available.', 'Kullanılabilir piyasa verisi yok.'],
  ['Failed to load petitions', 'Dilekçeler yüklenemedi'],
  ['No upgrade proposals on chain.', 'Zincirde yükseltme önerisi yok.'],
  ['Auto-snapshots are running.', 'Otomatik anlık görüntüler çalışıyor.'],
  ['No petitions on the chain yet.', 'Zincirde henüz dilekçe yok.'],
  ['Wormhole turns on the obfuscated lane for gates and the obfuscated commons.', 'Wormhole, geçitler ve genel alan için gizlenmiş iletişim hattını etkinleştirir.'],
  ['public mesh and perimeter feeds.', 'genel mesh ve çevre akışları.'],
  ['Wormhole lane active. Gate chat is available on this lane, but metadata resistance is reduced until Reticulum is ready.', 'Wormhole hattı etkin. Geçit sohbeti bu hatta kullanılabilir; Reticulum hazır olana kadar üstveri koruması sınırlıdır.'],
  ['Wormhole and Reticulum are both ready. Dead Drop / DM requires this tier for the strongest content and transport privacy.', 'Wormhole ve Reticulum hazır. Dead Drop / DM, en güçlü içerik ve aktarım gizliliği için bu seviyeyi gerektirir.'],
  ['Sentinel Hub gives you access to ESA satellite imagery', 'Sentinel Hub, ESA uydu görüntülerine erişim sağlar'],
  ['Sentinel credentials are configured on the backend. The dashboard fetches tokens automatically; your browser does not handle the secret.', 'Sentinel kimlik bilgileri arka uçta yapılandırılmıştır. Panel belirteçleri otomatik alır; tarayıcı gizli anahtarı işlemez.'],
  ['Run connect in MeshTerminal first, or open', 'Önce MeshTerminal içinde bağlantıyı çalıştırın veya açın'],
  ['stronger PRIVATE / STRONG tier and is managed separately.', 'daha güçlü ÖZEL / GÜÇLÜ seviyesindedir ve ayrı yönetilir.'],
  ['Active direct target:', 'Etkin doğrudan hedef:'],
  ['Type in the input below and press send, or clear it to return to channel broadcast.', 'Aşağıdaki alana yazıp gönderin; kanal yayınına dönmek için hedefi temizleyin.'],
  ['No messages from ', 'Şuradan henüz mesaj yok: '],
  ['No public direct messages addressed to ', 'Şu adrese gönderilmiş genel doğrudan mesaj yok: '],
  ['Public Mesh key is ready, but MQTT is off.', 'Genel Mesh anahtarı hazır ancak MQTT kapalı.'],
  ['Enable MQTT in Settings to join the live public lane.', 'Canlı genel hatta katılmak için Ayarlar bölümünden MQTT’yi etkinleştirin.'],
  ['MQTT bridge connected.', 'MQTT köprüsü bağlandı.'],
  ['MQTT bridge enabled. Connection may take a few seconds.', 'MQTT köprüsü etkin. Bağlantı birkaç saniye sürebilir.'],
  ['MQTT bridge disabled.', 'MQTT köprüsü devre dışı.'],
  ['Native vault unavailable in browser mode.', 'Tarayıcı modunda yerel güvenli kasa kullanılamaz.'],
  ['Secret values are write-only from the WebView', 'Gizli değerler WebView üzerinden yalnızca yazılabilir'],
  ['NOT CONNECTED', 'BAĞLI DEĞİL'],
  ['CONNECTED ', 'BAĞLI '],
  ['PROTECTED AT REST', 'DİSKTE KORUMALI'],
  ['DEGRADED CUSTODY', 'SINIRLI YEREL KORUMA'],
  ['Click to delete', 'Silmek için tıklayın'],
  ['Secret value', 'Gizli değer'],
  ['NOTIFICATIONS ENABLED', 'BİLDİRİMLER ETKİN'],
  ['ENABLE NOTIFICATIONS', 'BİLDİRİMLERİ ETKİNLEŞTİR'],
  ['LOCAL DESKTOP NOTIFICATIONS', 'YEREL MASAÜSTÜ BİLDİRİMLERİ'],
  ['WINDOWS SECRET VAULT', 'WINDOWS GÜVENLİ KASASI'],
  ['OPENCTI INTEGRATION', 'OPENCTI ENTEGRASYONU'],
  ['RUNTIME PROFILE', 'ÇALIŞMA PROFİLİ'],
  ['OFFLINE MODE', 'ÇEVRİMDIŞI MOD'],
  ['METERED NETWORK', 'ÖLÇÜMLÜ AĞ'],
  ['BACKEND ADMIN KEY NOT CONFIGURED', 'ARKA UÇ YÖNETİCİ ANAHTARI YAPILANDIRILMAMIŞ'],
  ['ADMIN KEY INVALID OR EXPIRED', 'YÖNETİCİ ANAHTARI GEÇERSİZ VEYA SÜRESİ DOLMUŞ'],
  ['ADMIN SESSION REQUIRED', 'YÖNETİCİ OTURUMU GEREKLİ'],
  ['ADMIN SESSION FAILED', 'YÖNETİCİ OTURUMU BAŞARISIZ'],
  ['LOCAL SESSION PRIMED', 'YEREL OTURUM HAZIR'],
  ['Protected settings request failed', 'Korumalı ayarlar isteği başarısız'],
  ['Model:', 'Model:'],
  ['Classification:', 'Sınıflandırma:'],
  ['Altitude:', 'İrtifa:'],
  ['Speed:', 'Hız:'],
  ['Registration:', 'Tescil:'],
  ['Source:', 'Kaynak:'],
  ['Confidence:', 'Güven:'],
  ['Threats in area', 'Bölgedeki tehditler'],
  ['No local rules yet.', 'Henüz yerel kural yok.'],
  ['No analyst workspace presets yet.', 'Henüz analist çalışma alanı önayarı yok.'],
  ['Search cases, incidents, evidence...', 'Dosya, olay ve kanıt ara...'],
  ['Paste local intelligence text to summarize...', 'Özetlenecek yerel istihbarat metnini yapıştırın...'],
  ['Ollama model name (for example model:tag)', 'Ollama model adı (örnek model:etiket)'],
  ['Ollama is not running on localhost.', 'Ollama yerel makinede çalışmıyor.'],
  ['Search posts or type g/[gate] to jump...', 'Gönderilerde ara veya geçide gitmek için g/[geçit] yaz...'],
  ['Post into this gate...', 'Bu geçide gönder...'],
  ['Search ALL Polymarket + Kalshi markets', 'TÜM Polymarket + Kalshi piyasalarında ara'],
  ['reason (max 2000 chars)', 'gerekçe (en fazla 2000 karakter)'],
  ['evidence hash (e.g. ipfs://… or sha256:…)', 'kanıt özeti (örn. ipfs://… veya sha256:…)'],
  ['Updated ', 'Güncellendi '],
  ['unknown quant', 'bilinmeyen niceleme'],
];

function translateUiValue(value: string): string {
  const trimmed = value.trim();
  const exact = EXACT[trimmed] || I18N_REVERSE[trimmed];
  if (exact) return exact;
  let next = trimmed;
  next = next.replace(/ALERT LVL\s*:?\s*(\d+)/gi, 'UYARI SEVİYESİ $1');
  next = next.replace(/ACTIVE THREATS IN AREA/gi, 'BÖLGEDE AKTİF TEHDİT');
  next = next.replace(/(\d+) snapshots? ready/gi, '$1 anlık görüntü hazır');
  next = next.replace(/snapshot(s)?/gi, (m) => m.toLowerCase().endsWith('s') ? 'anlık görüntüler' : 'anlık görüntü');
  for (const [from, to] of UI_PHRASES) {
    if (next.includes(from)) next = next.replace(from, to);
  }
  return next;
}

const ATTRS = ['title', 'aria-label', 'placeholder'] as const;

function translateTextNode(node: Text): void {
  const parent = node.parentElement;
  if (!parent) return;
  const raw = node.nodeValue || '';
  const trimmed = raw.trim();
  const translated = translateUiValue(trimmed);
  if (!translated || translated === trimmed) return;
  const lead = raw.match(/^\s*/)?.[0] ?? '';
  const trail = raw.match(/\s*$/)?.[0] ?? '';
  node.nodeValue = `${lead}${translated}${trail}`;
}

function translateElement(el: Element): void {
  for (const attr of ATTRS) {
    const current = el.getAttribute(attr);
    if (!current) continue;
    const translated = translateUiValue(current.trim());
    if (translated && translated !== current.trim()) el.setAttribute(attr, translated);
  }

  for (const child of Array.from(el.childNodes)) {
    if (child.nodeType === Node.TEXT_NODE) translateTextNode(child as Text);
  }
}

function translateTree(root: ParentNode): void {
  if (root instanceof Element) translateElement(root);
  root.querySelectorAll?.('button,label,option,summary,th,td,legend,h1,h2,h3,h4,h5,h6,span,p,div,a,li,[role="button"],[role="tab"],[title],[aria-label],[placeholder]')
    .forEach(translateElement);
}

export default function TurkishUiBridge() {
  const { locale } = useTranslation();

  useEffect(() => {
    if (locale !== 'tr' || typeof document === 'undefined') return;
    translateTree(document.body);
    const observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        for (const node of Array.from(mutation.addedNodes)) {
          if (node instanceof Element) translateTree(node);
          else if (node.nodeType === Node.TEXT_NODE) translateTextNode(node as Text);
        }
      }
    });
    observer.observe(document.body, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, [locale]);

  return null;
}
